Revert "Fix 2nd command not executed when 1st command fail" This reverts commit d325129a0678f16c2e2a67bf4169bf34b0a96501.

diff --git a/.github/workflows/build-openwrt-cache.yml b/.github/workflows/build-openwrt-cache.yml
--- a/.github/workflows/build-openwrt-cache.yml
+++ b/.github/workflows/build-openwrt-cache.yml
@@ -127,8 +127,8 @@ jobs:
         cd openwrt
         echo -e "$(($(nproc)+1)) thread compile"
         set -o pipefail
-        { make tools/install -j$(($(nproc)+1)) || make tools/install -j1 V=s CONFIG_DEBUG_SECTION_MISMATCH=y ; } 2>&1 | tee build.log | grep -i -E "^make.*(error|[12345]...Entering dir|'conf'|s/config'|world)|^ make|^ +error"
-        { make toolchain/install -j$(($(nproc)+1)) || make toolchain/install -j1 V=s CONFIG_DEBUG_SECTION_MISMATCH=y ; } 2>&1 | tee build.log | grep -i -E "^make.*(error|[12345]...Entering dir|'conf'|s/config'|world)|^ make|^ +error"
+        { make tools/install -j$(($(nproc)+1)) | tee build.log ; } || { make tools/install -j1 V=s CONFIG_DEBUG_SECTION_MISMATCH=y 2>&1 | tee verbose.log | grep -i -E "^make.*(error|[12345]...Entering dir)" ; }
+        { make toolchain/install -j$(($(nproc)+1)) | tee build.log ; } || { make toolchain/install -j1 V=s CONFIG_DEBUG_SECTION_MISMATCH=y 2>&1 | tee verbose.log | grep -i -E "^make.*(error|[12345]...Entering dir)" ; }
         set +o pipefail
         echo "status=success" >> $GITHUB_OUTPUT
 
diff --git a/.github/workflows/build-openwrt-m4a.yml b/.github/workflows/build-openwrt-m4a.yml
--- a/.github/workflows/build-openwrt-m4a.yml
+++ b/.github/workflows/build-openwrt-m4a.yml
@@ -137,7 +137,7 @@ jobs:
         cd openwrt
         echo -e "$(($(nproc)+1)) thread compile"
         set -o pipefail
-        { make -j$(($(nproc)+1)) || make -j1 V=s CONFIG_DEBUG_SECTION_MISMATCH=y ; } 2>&1 | tee build.log | grep -i -E "^make.*(error|[12345]...Entering dir|'conf'|s/config'|world)|^ make|^ +error"
+        { make -j$(($(nproc)+1)) | tee build.log ; } || { make -j1 V=s CONFIG_DEBUG_SECTION_MISMATCH=y 2>&1 | tee verbose.log | grep -i -E "^make.*(error|[12345]...Entering dir)" ; }
         set +o pipefail
         echo "status=success" >> $GITHUB_OUTPUT
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
